8304389: [11u] Crash on Windows in C2 compiled code after 8248238 and…
openjdk/jdk11u pull request #70
Opened 2023-03-17 07:47 UTC by GoeLin

… 8218431

A required fix to avoid regression in 11.0.19. See JBS issue.

2023-03-17 22:53 UTC, dean-long requested changes
It sounds like the real problem is the #ifdef _WIN64 in x86_64.ad.  If that code is wrong for 64-bit Windows, shouldn't it be removed?

2023-03-20 15:28 UTC, GoeLin commented
Hi @dean-long 
I am not yet completely sure what is really wrong. The point is that the test only crashes in 11 since we enabled the #ifdef by accident.  It is enabled in 16+, too, but going back all the way to starting development of 16 we don't have a single crash in that code.  In 11, it is 100% reproducible. So I assumed there is another part missing that should be backported, too.
As release of 11.0.19 is coming up, I first want to undo the change in 11 to avoid the regression.

2023-03-20 19:01 UTC, GoeLin commented
Actually, the configuration leading to errors exactly implements the calling conventions as speified here https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#callercallee-saved-registers .

The other configuration, doing more save-on-call, is always correct, but inefficient in case the registers are also saved-on-entry. In that case the registers are saved twice.

2023-03-21 00:05 UTC, dean-long commented
There is probably some x64 code that is assuming Linux ABI for RSI and RDI, so it breaks when trying to use the Windows ABI.  And the _WIN64 ABI settings in x86_64.ad may be effectively dead code that was never tested because of the makefile issue that never defined _WIN64 for adlc before.

2023-03-21 00:21 UTC, dean-long commented
Nevermind, I think you're right, these _WIN64 ABI settings have been enabled in C2 since jdk16, so it's not clear why there is a problem only in 11u.

2023-03-21 00:56 UTC, dean-long commented
@GoeLin, after more consideration, your fix does seem safest.  However, it might help to have a comment explaining why that change has been disabled.  So it might be better to comment out that .gmk logic rather than delete it.

2023-03-21 07:23 UTC, GoeLin commented
Hi @dean-long, if I comment it out, it is no more set on aarch64.
I can add a comment pointing to this bug though.
But maybe it is better to fiddle with the ad file as you say.
In case a later backport brings new #ifdef _WIN64 coding to the ad files.
Currently, the problematic switch is the only occurance.

By the way, as I said in the JBS issue, I think the change making the difference in 16 is "[JDK-8256205](https://bugs.openjdk.org/browse/JDK-8256205): Simplify compiler calling convention handling"

2023-03-21 07:36 UTC, dean-long commented
Yes, you need _WIN64 set for windows-aarch64 even if you comment out or remove the isTargetCpuBits block.

My concern with just changing just the .ad file is there are other uses of #ifdef _WIN64 in x86 .hpp header files that adlc files might include directly or indirectly.

To me JDK-8256205 just looks like a refactoring.  I don't see how it would change the calling convention.

2023-03-21 07:49 UTC, GoeLin commented
Hi
I pushed a new change.  #if 0 is not supported by adlc, therefore #ifdef WRONG

> My concern with just changing just the .ad file is there are other uses of #ifdef _WIN64 in x86 .hpp header files that adlc files might include directly or indirectly.
adlc reads the ad file, evaluates the _WIN64, swallows it and outputs C++ files without that define.
The C++ build compiling the generated files has _WIN64 set anyways, already before the trouble we look at here.

2023-03-21 07:58 UTC, dean-long approved these changes
OK, this looks reasonable.  Instead of #ifdef WRONG, how about something like #ifdef DISABLED instead?
I suggest filing a separate bug/RFE to investigate the reason for the crash.
Finally, please get a 2nd review.

2023-03-21 13:27 UTC, TheRealMDoerr approved these changes
Ok. There seems to be code which clobbers at least RSI in 11u. Having the caller preserve these registers over runtime calls looks like a feasible workaround. I think this is a good fix for the 11u release. I'd use `#if 0` instead of checking for `DISABLED`.

2023-03-21 14:17 UTC, GoeLin commented
Hi Martin, 
adlc implements checking #ifdef.  It can not parse #if. Therefore, as I stated above, #if 0 is not working.
Thanks for your review!

2023-03-21 14:40 UTC, GoeLin commented
/integrate

2023-03-21 14:42 UTC, closed without merging

2023-03-21 15:10 UTC, TheRealMDoerr commented
This fix is also missing in 11u: https://bugs.openjdk.org/browse/JDK-8254252